/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

//        ArrayList<String> contatos = new ArrayList<>();
//
//        contatos.add("Juca");
//        contatos.add("Ana");
//        contatos.add("Pedro");
//
//        System.out.println("Total de contato = " + contatos.size());
//
//        if(contatos.contains("Ana")){
//            System.out.println("Ana já esta em sua lista de contatos!");
//        }
//
//        int i = contatos.indexOf("Ana");
//
//        contatos.remove("Ana");
//
//        if(contatos.contains("Ana")){
//            System.out.println("Ana já esta em sua lista de contatos!");
//        } else{
//            System.out.println("Não");
//        }
//
//        for (int j = 0; j < contatos.size(); j++) {
//            System.out.println(contatos.get(j));
//        }
//
//        //For each
//        for (var  elemento: contatos){
//            System.out.println(elemento);
//        }
//
//        contatos.forEach(elemento ->{
//            System.out.println("Nome: " + elemento );
//        });
//
////        method reference
//
//        contatos.forEach(System.out::println);
//
//        contatos.removeIf(e->e.equals("Juca"));
//        contatos.forEach(System.out::println);
//        contatos.add("Ana");
//        contatos.add("Juca");
//
//        Collections.sort(contatos);
//        contatos.forEach(System.out::println);
//
//        Collections.shuffle(contatos);
//        contatos.forEach(System.out::println);


//        Fazer um programa que vai ficar lendo do teclado N números que o usuário digitar e todo número digitado dev e ser guardado em uma ArrayLista, e caso ele digite o número 999 o programa deve imprimir todos os números digitados pela pessoa


        ArrayList<Integer> numeros = new ArrayList<>();

        int k = 0;
        System.out.println("Entre com n números interiros, e quando quiser parar de digitar, entre com o número \"999\":");
        Scanner teclado = new Scanner(System.in);
        k = teclado.nextInt();
        while (k != 999){
            numeros.add(k);
            k = teclado.nextInt();
        }


        System.out.println("Os número digitados foram: ");
        numeros.forEach(e-> System.out.print(e + " "));


        // Faça um programa onde o usuário irá digitar um conjunto de número de quando for digitado 999 deve ser impresso na sequência inversa na qual a pessoa entrou



    }
}
