/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.javaOfEmpires.Aldeao;
import engtelecom.poo.javaOfEmpires.Arqueiro;
import engtelecom.poo.javaOfEmpires.Caveleiro;
import engtelecom.poo.javaOfEmpires.Personagem;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<Personagem> personagens = new ArrayList<>();

        personagens.add(new Aldeao());
        personagens.add(new Arqueiro());
        personagens.add(new Caveleiro());

        for(Personagem p: personagens){
            System.out.println(p.atacar());
            System.out.println(p.mover() + "\n");
        }

    }
}
