/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;

public class App {
    private Carro carro;
    private ArrayList<Motor> motores;


    public App() {
        this.motores = new ArrayList<>();
        this.carro = new Carro("Laranja",new Motor("Padrão",100),"McLaren");
    }

    public void trocaMotor(Motor m){
        this.motores.add(this.carro.getMotor());
        this.carro.setMotor(m);
    }

    public void trocarCarro(Carro c){
        this.carro = c;
    }

    public static void main(String[] args) {
        App app = new App();

        app.trocaMotor(new Motor("Ferrari",400));
        app.trocaMotor(new Motor("Lamborghini",700));

        app.motores.forEach(System.out::println);

    }
}
