/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Scanner;

public class App1 {

    public static void main(String[] args) {

        try(Scanner arq = new Scanner(App1.class.getClassLoader().getResourceAsStream("produto.txt"))) {
            while (arq.hasNext()){
                System.out.println(arq.nextLine());
            }
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }

    }

}
