/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.Scanner;

public class App {
    private static Agenda agenda;

    public App(){
        this.agenda = new Agenda();
    }


    public static void main(String[] args) {
        App app = new App();


    }
}
