/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {



    }
}
