    /*
     * This Java source file was generated by the Gradle 'init' task.
     */
    package engtelecom.poo;

    public class App {

        public static void main(String[] args) {

            Retangulo r = new Retangulo(8,3,"OLA");

            System.out.println(r.getAltura() + " " + r.getLargura() + " " + r.getCodificacao());
            System.out.println(r.toString());

        }

    }
