/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    private static final int SEG = 1;
    private static final int QUA = 3;

    public static void main(String[] args) {
    int[] dias = {SEG,QUA};

    DiaDaSemana[] diaDaSemana = new DiaDaSemana[]{DiaDaSemana.SEG, DiaDaSemana.QUA};

    Disciplina d = new Disciplina("POO", diaDaSemana);

        System.out.println(d);

        for (DiaDaSemana a : DiaDaSemana.values()){
            System.out.println(a);
        }

    }

}
