/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.pilha;

public class App {

    public static void main(String[] args){
        Pilha<String> teste1 = new Pilha<>(2);

        try{
//            teste1.getTopo();
            System.out.println(teste1.isEmpty());
            teste1.empilhar("Olá");
            System.out.println(teste1.getTopo());
//            teste1.empilhar("Olá4314");
            System.out.println(teste1.getTopo());
//            teste1.empilhar("ogka");

//            teste1.desempilhar();
//          teste1.desempilhar();
//          teste1.desempilhar();
        } catch (PilhaVaziaException e ){
            System.err.println("Erro: " + e.getMessage());
        }catch (PilhaCheiaException e){
            System.err.println("Erro: " + e.getMessage());
        }

        Pilha<Pessoa> pessoaPilha = new Pilha<>(2);

        try {
            pessoaPilha.empilhar(new Pessoa("Guerra","102","egnri@gmail.com"));
            pessoaPilha.empilhar(new Pessoa("Juca","230","juca@gmail.com"));
//            pessoaPilha.empilhar(new Pessoa("igfrni","43124","rtb42489123"));
            pessoaPilha.desempilhar();
            pessoaPilha.desempilhar();
            pessoaPilha.desempilhar();

        } catch (PilhaCheiaException e) {
            System.err.println("Erro: " + e.getMessage());
        } catch (PilhaVaziaException e) {
           System.err.println("Erro: " + e.getMessage());
        }
    }
}
