/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.junit.jupiter.api.Test;

class App1Test {
    @Test void appHasAGreeting() {
        App1 classUnderTest = new App1();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
