/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.javaofempires;

import engtelecom.poo.javaofempires.personagens.*;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<Personagem> personagens = new ArrayList<>();

        personagens.add(new Aldeao());
        personagens.add(new Arqueiro());
        personagens.add(new Caveleiro());

        for(Personagem p: personagens){
            if(p instanceof Guerreiro){
                System.out.println(((Guerreiro) p) .atacar());
            }

            System.out.println(p.mover() + "\n");
        }

    }
}
